### ISSUE TITLE
BetterAuth Middleware and Session errors

### ISSUE THREAD

**Issue by Ale1x** [haydenbleasel/next-forge#384]
**Describe the bug**
I followed the guide in the next-forge docs then i'm getting the following errors

**next-forge version**
3.0.9 (latest)

**To Reproduce**
1. Follow guide on how to switch from clerk to betterauth

**Expected behavior**
Error not happening

**Screenshots**
![{A662EF0F-4529-43D4-98B3-0245D0419ED0}](https://github.com/user-attachments/assets/e6314f8c-9c20-460c-bac3-4c84f2f68fe6)
![{6BCE23DF-B6D6-4F2D-8F6E-950DBA002BAF}](https://github.com/user-attachments/assets/f6879b7b-931e-4e64-bd78-dcb4305ed673)

**Desktop (please complete the following information):**
 - OS: Windows 11 PRO 24H2
  - Browser: brave 1.73.104

**Comment by haydenbleasel** [comment]
@Ale1x Possibly resolved in the fix for #386. Would you be able to verify for me by checking out the latest migration docs?

**Comment by mikestecker** [comment]
I'm seeing a number of other errors as well. This is with the latest from the docs

```
  ⨯ [Error: The Middleware "/middleware" must export a `middleware` or a `default` function]
│ TypeError: Cannot read properties of undefined (reading 'origin')
│     at authMiddleware (packages/auth/middleware.ts:9:63)
│     at <unknown> (apps/web/middleware.ts:22:30)
│    7 |
│    8 | export const authMiddleware = async (request: NextRequest) => {
│ >  9 |   const url = new URL('/api/auth/get-session', request.nextUrl.origin);
│      |                                                               ^
│   10 |   const response = await fetch(url, {
│   11 |     headers: {
│   12 |       cookie: request.headers.get('cookie') || '',
│  ⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'origin')
│     at authMiddleware (packages/auth/middleware.ts:9:63)
│     at <unknown> (apps/web/middleware.ts:22:30)
│    7 |
│    8 | export const authMiddleware = async (request: NextRequest) => {
│ >  9 |   const url = new URL('/api/auth/get-session', request.nextUrl.origin);
│      |                                                               ^
│   10 |   const response = await fetch(url, {
│   11 |     headers: {
│   12 |       cookie: request.headers.get('cookie') || '',
│  ⨯ unhandledRejection:  TypeError: Cannot read properties of undefined (reading 'origin')
│     at authMiddleware (packages/auth/middleware.ts:9:63)
│     at <unknown> (apps/web/middleware.ts:22:30)
│    7 |
│    8 | export const authMiddleware = async (request: NextRequest) => {
│ >  9 |   const url = new URL('/api/auth/get-session', request.nextUrl.origin);
│      |                                                               ^
│   10 |   const response = await fetch(url, {
│   11 |     headers: {
│   12 |       cookie: request.headers.get('cookie') || '',
```

**Comment by mikestecker** [comment]
<img width="1141" alt="Screenshot 2025-01-06 at 6 50 45 PM" src="https://github.com/user-attachments/assets/f0674029-34b2-409e-9fad-9124df834169" />

**Comment by Lukem121** [comment]
Check out the Better Auth docs @ https://www.better-auth.com/docs/integrations/next#middleware

**Comment by barsketis** [comment]
I believe this issue was fixed in https://github.com/haydenbleasel/next-forge/releases/tag/v3.2.26 for the app directory @haydenbleasel 

@mikestecker @Ale1x just import the type and export the function as a NextMiddleware as shown below
```
import { NextMiddleware } from 'next/server';

export default authMiddleware(() => securityHeaders()) as unknown as NextMiddleware;
```

**Comment by Lukem121** [comment]
@barsketis I'm not sure if this is helpful, but here's what I'm currently doing:

```
export default async function authMiddleware() {
  const securityResponse = await securityHeaders();

  if (securityResponse.status !== 200) {
    return securityResponse;
  }

  return NextResponse.next();
}
```

**Comment by mikestecker** [comment]
@barsketis @haydenbleasel I'm still seeing an issue. I have even attempted to start from scratch with the latest build, followed the Better Auth migration steps and now I'm seeing the following error:

<img width="981" alt="Image" src="https://github.com/user-attachments/assets/33fda2ab-7a90-4332-8dba-e2cbc8f98a30" />

**Comment by haydenbleasel** [comment]
@mikestecker checking it out now, thanks for confirming 👍

**Comment by sneddonisaac** [comment]
Do we have an update on this as I am still having this exact issue when trying to migrate to BetterAuth, it looks like a fantastic auth package but I just can't get it to work

**Comment by RicSala** [comment]
Same here...

**Comment by sneddonisaac** [comment]
@RicSala & @haydenbleasel So I have managed to get it to work in my next forge application but it isn't pretty and much more of a machete solution than that of a scalpel. I will post how I did this a bit later on as currently busy :)

**Comment by Charuru** [comment]
> [@RicSala](https://github.com/RicSala) & [@haydenbleasel](https://github.com/haydenbleasel) So I have managed to get it to work in my next forge application but it isn't pretty and much more of a machete solution than that of a scalpel. I will post how I did this a bit later on as currently busy :)

Any updates on this

**Comment by claytonrothschild** [comment]
Something like this should work (it works for me).

auth/middleware.ts:
```typescript
import { getSessionCookie } from "better-auth/cookies";
import { type NextRequest, NextResponse } from "next/server";

// List of public routes that don't require authentication
const PUBLIC_ROUTES = ["/login", "/signup", "/api/auth"];

export async function authMiddleware(request: NextRequest) {
	const sessionCookie = getSessionCookie(request);
	const { pathname } = request.nextUrl;

	// Check if the path is in the authenticated group
	const isAuthenticatedRoute = pathname.startsWith("/(authenticated)");
	// Check if the path is in the unauthenticated group
	const isUnauthenticatedRoute = pathname.startsWith("/(unauthenticated)");

	// Allow access to public routes
	if (PUBLIC_ROUTES.some((route) => pathname.startsWith(route))) {
		// Redirect to dashboard if user is already logged in and tries to access login/signup
		if (sessionCookie && ["/login", "/signup"].includes(pathname)) {
			return NextResponse.redirect(new URL("/dashboard", request.url));
		}
		return NextResponse.next();
	}

	// Handle authenticated routes
	if (isAuthenticatedRoute) {
		if (!sessionCookie) {
			return NextResponse.redirect(new URL("/login", request.url));
		}
		return NextResponse.next();
	}

	// Handle unauthenticated routes
	if (isUnauthenticatedRoute) {
		if (sessionCookie) {
			return NextResponse.redirect(new URL("/dashboard", request.url));
		}
		return NextResponse.next();
	}

	return NextResponse.next();
}

export const config = {
	matcher: [
		/*
		 * Match all request paths except for the ones starting with:
		 * - _next/static (static files)
		 * - _next/image (image optimization files)
		 * - favicon.ico (favicon file)
		 * - public folder
		 */
		"/((?!_next/static|_next/image|favicon.ico|public/).*)",
		// Match all routes in the authenticated and unauthenticated groups
		"/(authenticated)/:path*",
		"/(unauthenticated)/:path*",
	],
};
```

app/middleware.ts:
```typescript
import { authMiddleware } from '@repo/auth/middleware';
import {
  noseconeMiddleware,
  noseconeOptions,
  noseconeOptionsWithToolbar,
} from '@repo/security/middleware';
import type { NextRequest } from 'next/server';
import { env } from './env';

const securityHeaders = env.FLAGS_SECRET
  ? noseconeMiddleware(noseconeOptionsWithToolbar)
  : noseconeMiddleware(noseconeOptions);

export default async function middleware(request: NextRequest) {
  // Run auth middleware first
  const authResponse = await authMiddleware(request);
  if (authResponse) return authResponse;

  // Then run security headers
  const securityResponse = await securityHeaders();
  if (securityResponse) return securityResponse;

  return null;
}

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    // Always run for API routes
    '/(api|trpc)(.*)',
  ],
};
```

There is some redundency above, but this should get you going past the error.

**Comment by jpvalery** [comment]
Tried the documented migration as well as the one on better-auth website—ran into similar errors. 

One thing that help was to uncomment the server-only on the database (i had forgotten to do it). But yeah, seems like something is not quite right with the current docs. 

Would be nice for the base version of next-forge to use better-auth and then have a migration to clerk—as this path might be easier than the otherway around.

**Comment by ph1losof** [comment]
Same problem in `5.0.2`

**Comment by ph1losof** [comment]
for anybody interested in the solution, I have managed to get it to work using following `packages/auth/middleware.ts`:

```ts
import { getSessionCookie } from "better-auth/cookies";
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export function authMiddleware(
  middlewareFn?: (
    _auth: { req: NextRequest; authorized: boolean },
    request: NextRequest,
  ) => Promise<Response> | Response,
) {
  return async function middleware(request: NextRequest) {
    const sessionCookie = getSessionCookie(request);
    const authorized = Boolean(sessionCookie);

    if (middlewareFn) {
      const response = await middlewareFn(
        { req: request, authorized },
        request,
      );

      if (
        response &&
        (!response.headers.get("x-middleware-next") ||
          response.headers.get("Location"))
      ) {
        return response;
      }
    }

    if (!sessionCookie) {
      return NextResponse.redirect(new URL("/sign-in", request.url));
    }

    return NextResponse.next();
  };
}
```

All other middlewares seem to work as expected, you don't have to change anything else

**Comment by ph1losof** [comment]
> Tried the documented migration as well as the one on better-auth website—ran into similar errors.
> 
> One thing that help was to uncomment the server-only on the database (i had forgotten to do it). But yeah, seems like something is not quite right with the current docs.
> 
> Would be nice for the base version of next-forge to use better-auth and then have a migration to clerk—as this path might be easier than the otherway around.

I agree that it should become the default, clerk is a third-party SaaS, such provider shouldn't be a part of open-source base package. Same thing applies for stripe integration. 

Since it is too drastic of a change as of now, I think that there should be at least a CLI that does all migrations by itself at the stage of init

**Comment by jpvalery** [comment]
@t3ntxcl3s thanks for sharing your solution! (I just finished recreating my /app from scratch from the better-auth nextjs demo 😂 alas, I'll likely stick to that version now).

Are there any other changes you made with your solution? Is your provided code based on the next-forge docs?

**Comment by ph1losof** [comment]
> [@t3ntxcl3s](https://github.com/t3ntxcl3s) thanks for sharing your solution! (I just finished recreating my /app from scratch from the better-auth nextjs demo 😂 alas, I'll likely stick to that version now).
> 
> Are there any other changes you made with your solution? Is your provided code based on the next-forge docs?

The provided code is not based on the next-forge docs, it was inspired from clerk middleware implementation. Basically, all it does - allows to receive and run middlewares, before running `better-auth` checks for cookies. The behavior is supposed to stay the same and support all current middlewares - `packages/internationalization/middleware.ts` and `packages/security/middleware.ts`

There are no other changes required, only changing `packages/auth/middleware.ts` to the one I sent, it should fix the issue.
